FROM --platform=$BUILDPLATFORM node:14
# wersja node'a jest pobierana na dany system, więcej nie udało się zrobić, ponieważ moja aplikacja nie kompiluje się

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "start"]

EXPOSE 3000
