name: FibCalc

on:
  push:
    branches: [main]
    tags: 
       - 'v*'

jobs:
  build-push-images:
    name: Budowa i publikacja obrazow na repozytorium
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/fibcalc
            ghcr.io/${{ secrets.GHCR_USERNAME }}/fibcalc
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      
      - name: Build and push 
        id: docker_build
        uses: docker/build-push-action@v2 
        with:
          context: ./
          file: ./FibCalc/Dockerfile
          cache-from: type=registry, ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/fibcalc:latest
          cache-to: type=registry, ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/fibcalc:latest
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
